# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Founders and Coders Monthly Events
email: your-email@domain.com
description: Fac Alumni monthly events
baseurl: "/monthly" # the subpath of your site, e.g. /blog
url: "http://foundersandcoders.com" # the base hostname & protocol for your site
twitter_username: founderscoders

# Build settings
markdown: kramdown
